name: clang-tidy-post

on:
  workflow_run:
    # The name field of the lint action
    workflows: ['clang-tidy-review']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: ZedThree/clang-tidy-review/post@v0.19.0
        # lgtm_comment_body, max_comments, and annotations need to be set on the posting workflow in a split setup
        with:
          # adjust options as necessary
          annotations: false
          max_comments: 15
